name: Merge hotfix and main

on:
  workflow_dispatch:

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure user for git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Merge main into hotfix
        run: |
          git fetch origin
          git checkout hotfix
          git pull origin hotfix
          git fetch origin main
          if ! git diff --quiet origin/main..hotfix; then
            git merge --no-ff origin/main -m "Merge main into hotfix"
            git push origin hotfix
          else
            echo "No changes to merge from main to hotfix"
          fi

      - name: Merge hotfix into main
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git fetch origin hotfix
          if ! git diff --quiet origin/hotfix..main; then
            git merge --no-ff origin/hotfix -m "Merge hotfix into main"
            git push origin main
          else
            echo "No changes to merge from hotfix to main"
          fi
