name: SonarQube analysis

on:
  push:
    branches:
      - '**'

permissions: read-all

jobs:
  build:
    name: SonarQube analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: |
          ./gradlew clean build

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=src/main/
            -Dsonar.tests=src/test/
            -Dsonar.coverage.exclusions=**/vo/**,**/config/**,**/enums/**,**/log/**,**/utils/**,**/constants/**,**/TemplateApplication.kt
            -Dsonar.junit.reportPaths=build/test-results/test
            -Dsonar.java.coveragePlugin=jacoco
            -Dsonar.coverage.jacoco.htmlReportPaths=build/reports/jacoco/test/html
            -Dsonar.branch.name=${{ github.ref_name }}